#!/bin/bash
#--------------------------------------
# CUSTOM .BASHRC SETTINGS
#--------------------------------------
# Enviroment Variables

# Location for dotfiles repo.
export DOTFILES="${HOME}/wsl-dotfiles"

# Editor for general usage
export EDITOR=vim

# Pager for manual
export MANPAGER="sh -c 'col -bx | bat -l man -p --pager=\"less -FR\"'"

#--------------------------------------
# Import configurations
bashrc_dir="${DOTFILES}/doc/bashrc"

# prompt
[ -s ${bashrc_dir}/bashrc_prompt ]  && source ${bashrc_dir}/bashrc_prompt
# go
[ -s ${bashrc_dir}/bashrc_go ]      && source ${bashrc_dir}/bashrc_go
# nvm
[ -s ${bashrc_dir}/bashrc_nvm ]     && source ${bashrc_dir}/bashrc_nvm
# fzf
[ -s ${bashrc_dir}/bashrc_fzf ]     && source ${bashrc_dir}/bashrc_fzf
# vivid
[ -s ${bashrc_dir}/bashrc_vivid ]   && source ${bashrc_dir}/bashrc_vivid

#--------------------------------------
# Aliases

# cd
alias ..="cd .."
# git
alias gst="git status"

#--------------------------------------
# Init commands
