#!/bin/bash
#--------------------------------------
# CUSTOM .BASHRC SETTINGS
#--------------------------------------
# Enviroment Variables

# Location for dotfiles repo.
# dotfiles repo should be in the HOME dir.
export DOTFILES="${HOME}/wsl-dotfiles"

# Editor for general usage
export EDITOR=vim

# 

#--------------------------------------
# Load configurations
bashrc_dir="${DOTFILES}/doc/bashrc/etc"

# Load all files from ${bashrc_dir} directory
if [ -d "${bashrc_dir}" ]; then
  for file in ${bashrc_dir}/*; do
    source "${file}"
  done
fi

#--------------------------------------
# Aliases

# cd
alias ..="cd .."
# git
alias gst="git status"

#--------------------------------------
# Init commands
