#!/bin/bash
#--------------------------------------
# CUSTOM .BASHRC SETTINGS
#--------------------------------------
# Enviroment Variables

# Location for dotfiles repo.
# dotfiles repo should be in the HOME dir.
export DOTFILES="${HOME}/wsl-dotfiles"

# Editor for general usage
export EDITOR=vim

# PATH
# For mybuild
mybuild_bin="${HOME}/.cache/mybuild/bin"
[ -d "${mybuild_bin}" ] && export PATH="$PATH:${mybuild_bin}"
# For pip
local_bin="${HOME}/.local/bin"
[ -d "${local_bin}" ] && export PATH="$PATH:${local_bin}"

#--------------------------------------
# Load configurations
bashrc_dir="${DOTFILES}/doc/bashrc/etc"

# Load all files from ${bashrc_dir} directory
if [ -d "${bashrc_dir}" ]; then
  for file in "${bashrc_dir}"/bashrc_*; do
    source "${file}"
  done
fi

#--------------------------------------
# Aliases

# cd
alias ..="cd .."
# git
alias gst="git status"

#--------------------------------------
# Init commands

# starship
if type "starship" >/dev/null 2>&1 ; then
  eval "$(starship init bash)"
fi
