#!/bin/bash
#--------------------------------------
# CUSTOM .BASHRC SETTINGS
# For fzf
#--------------------------------------

# locaiotns
fzf_bin="${DOTFILES}/.cache/.fzf/bin"
fzf_keybinds_path="${DOTFILES}/doc/fzf/key-bindings.bash"
fzf_completion_path="${DOTFILES}/doc/fzf/completion"

# set to $PATH
[ -d ${fzf_bin} ] && export PATH="$PATH:${fzf_bin}"

# key bindings
[ -s ${fzf_keybinds_path} ] && source ${fzf_keybinds_path}
# completion
[ -s ${fzf_completion_path} ] && source ${fzf_completion_path} 

export FZF_DEFAULT_OPTS="
--layout=reverse
--info=inline
--height=80%
--multi
--preview-window=:hidden
--preview '([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200'
--bind '?:toggle-preview'
--bind 'ctrl-a:select-all'
"

# fzf's command
export FZF_DEFAULT_COMMAND="fd --hidden --follow --exclude '.git' --exclude 'node_modules'"
# CTRL-T's command
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# ALT-C's command
export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND --type d"

#--------------------------------------
# Functions

# # find-in-file - usage: fif <SEARCH_TERM>
fif() {
  if [ ! "$#" -gt 0 ]; then
    echo "Need a string to search for!"
    return 1
  fi
  rg --files-with-matches --no-messages "$1" | fzf $FZF_PREVIEW_WINDOW --preview "rg --ignore-case --pretty --context 10 '$1' {}"
}
