#!/bin/bash
#--------------------------------------
# CUSTOM .BASHRC SETTINGS
# For go
#--------------------------------------
# Enviroment variables
export GOPATH="${HOME}/.cache/mygo"
export PATH="${PATH}:/usr/local/go/bin:${GOPATH}/bin"
