#!/bin/bash
#--------------------------------------
# CUSTOM .BASHRC SETTINGS
# For completion
#--------------------------------------
# Locations
bashrc_cache_dir="${HOME}/.cache/dotfiles/bash/completion"

# Load all files from ${bashrc_cache_dir} directory
if [ -d "${bashrc_cache_dir}" ]; then
  for file in "${bashrc_cache_dir}"/*; do
    source "${file}"
  done
fi
